### ISSUE TITLE
Centrework With Repeats

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#105]
I have started the next set of Reviews just to see how the basic structure works. The first two question in this chapter seem clear and use existing graphics. See uploaded file:

Review4.1-2.docx

If you want an easy place to start, these seem simple to implement.

**Comment by rsryman** [comment]
Another suggestion for questions: take page 30 Bars 1-2 only (to the first plié). Make three versions: a) repeat same side, b) repeat other side, c) repeat in reverse, Match to 3 animations and three sets of labels, format as previous question (4.2). 
We could have a Hangout to go through the rest of the chapter and see how we can take pieces to quiz readers.

**Comment by rryman** [comment]
As we discussed via the phone:
You will look at Review 5 and see if you still want the above question added.
Or you will see if it fits in Review 7 better (part-bar repeats, nested repeats, arms and feet repeated differently, reverse to the other side).
I have completed Review 5 as best I can and uploaded the updated book to Dropbox.
Please check out Review 5 and give me your feedback.
I am not too sure about section 5.3. Do you think there is any value in these two questions?
It is hard to fit longer sequences of notation into the smaller widget. I can't go any smaller on the animations without cutting off the feet.

**Comment by rsryman** [comment]
Page 57 Question 2 of 2. The text should be: Drag the label under the corresponding notation.

Page 58 Question 1 of 2. I think this is too obvious. All the reader needs to do is look at the starting direction faced. A greater challenge would be to put the 2 notation examples on separate pages and perhaps vary each so it could repeat another way (perhaps different arms or different ending to test FIN or exclusion bracket?) with the corresponding animation. I like Question 2 of 2; if we separate the two we could add more questions for each.

This is where I thought we needed more examples to quiz details about the Ch5 content.

**Comment by rsryman** [comment]
See update Gr Battement exercise, uploaded: Review5GrandBattement

We can use any of these, depending on real estate:
a) Repeat other side
b) Repeat in reverse (legs only)
c) Repeat other side with second ending

Let me know which you want and I'll do corresponding animations. 
If we use c) there will be other questions to ask.

**Comment by rryman** [comment]
For b) why wouldn't we use repeat reverse legs and same arms, i.e., the upper and lower markings?
Should we restate the direction sign in the second stave in the "empty" repeat bars, as you asked me to do in the Sissonne Ordinaire on Page 68?
I think if we do this then I am okay with using the top two examples.
This would work out well, as it will be an example using upper and lower markings and the glissé animations you gave me will be an example of reverse on the other side.
Thoughts?

**Comment by rsryman** [comment]
Duh, I forgot this was in this chapter. Yes for b) use repeat reverse legs
and same arms, i.e., the upper and lower markings.

OK to restate direction sign.

OK, let's use a) and b).

**Comment by rryman** [comment]
Sorry, I am confused. I gather you wanted the above example to replace what I had on page 58. I don't think it really works in the Chapter 5 Review because it deals with theory that hasn't been introduced until Chapter 6. What do you think about:
The same Maria Developpe example and then a second example based on it with... 
Grand battement (replacing developpe), grand rond de jambe en l'air (replacing foot passing knee and unfolding), arms lowering to en bas straight from 2nd and leg closing without raccourci.
Or would the animation look too weird doing grand battement in two counts and closing at the end in two counts?

**I just noticed an error in the text on this page. It should read something like:
Here are two alternate ways to notate the developpe and raccourci actions.**

We can still use the above example in Chapter 7, but it will be the second example based on Chapter 5 sequences rather than Chapter 7 sequences. We will have to make sure we use Chapter 7 material for the rest of the Chapter 7 Review.
