### ISSUE TITLE
Book 3 Mock-up

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#13]
Rhonda, I have uploaded a copy of BeneshForBalletBook3 to Dropbox to the "Rhonda" folder as I think I now have it in a state that you won't find too confusing.

I have pieced together the information from the "Book Outline" (word doc) and the old "Benesh for Ballet: Book 2" which had the repeats included.
I have tried to use blue text to keep track of what I have done and what needs to be updated.
I can't guarantee that all the links will work, but most of them should.
A few issues have come up re order of pages for the book, but I don't know if we can solve them upfront, or whether they will become apparent as we work our way through developing the book.

I am fine with finishing off the updates for the animation and notation of the repeated jumps, before proceeding with the rest of the book. I'll leave that decision up to you.

**Comment by rsryman** [comment]
1. The heading of the section page that follows the title page says "Benesh for Ballet: Book 2" --> 3
2. Page 5. Yes, update page when we finish Ch3 since we might use direction signs, etc. Let's use another CAP on "Foot-to-Floor" + In-Frame" + "Across-Frame"; consider deleting "at knee height" on this page since we actually used it in Book 2 (tour), cf Foot-to-Floor Relationship and In-Frame movement lines for legs and arms. As your intro implies, BB7 reviews and extends theory previously introduced. Delete final sentence in para 1 (redundant?).
3. Page 6. extra space between "the  sign" on line 1? Perhaps unbold "full" since it is not part of the caption for "pointes"? Just a thought: to keep it simple, I wonder if this page should show only a few examples of commonly used positions taken flat versus demi- versus pointes, and link to an Appendix containing a full set, as now on page 6-8? As we did for turn signs. Then we could do "pointe tendu" on page 7, and have room for images so the pages would look more interesting. 
4. Page 8. Can you check the current RAD syllabus to see if they are using "pointe tendu" or "pointe tendue" now? The latter is more correct (as used in Cecchetti).
5. Page 9. The 4 small graphics for closing behind/in front (lines 3 and 4) are swapped. We might prefer to use closing from pointe tendu side (closing devant/derrière with red right foot) if we want to show the animation from back view.
6. Page 10. Suggested edit re first sentence: To show a foot closing in…" To match the BMN to the text, we should introduce the drawing close (closing sign) first, then the relevé (static sign) – perhaps instead of the closing 3rd example, since this is rarely used. At the bottom of the page, before the "Note…" should we add a sentence like: "Remember to look at the placement of the open dot or vertical stroke – not the two-feet-together level sign." Perhaps repeat this on next page re 1st?
7. We might not need to introduce closing 1st demi- and full pointes if we use the layout suggested re page 6. To be discussed?
I suggest a Google Hangout to go through this together before I continue.
