### ISSUE TITLE
To Do's (once the beginning chapters are finished)

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#24]
**Table of Contents**
✔1) decide on notation example that best represents what the book is about and make it the background for the iBook Author "Table of Contents" section.
**I tried making the link font smaller to eliminate scrolling, but I had to go too small to make it work for all pages. I decided that it is better to have larger clearer text and have the reader scroll.**

**Allegro with Repeats Chapter:**
✔1) decide on the order for the allegro enchainements
✔2) decide what repeats we are going to use for each enchainement (each taking two or three pages)
✔3) decide if we going to use the animations again on the other pages
✔4) decide which pop-ups to keep in
✔5) check the notation of all endings
✔6) check the "i" boxes for wording of all endings

**Acknowledgements**
1) Update consultants and proofreaders.

**Glossary:**
✔1) decide which entries to keep and which to eliminate.

**About This Book**
✔1) Text of p. 4 is good, but will be revisited closer to publication.
✔2) We need to get farther into Book 3 before we decide on an example of notation and images for p. 1. 

**Somewhere in the book**
✔1) Add "redundancy avoidance" note the first time we use this device for port de bras, e.g., one hand joins the other in high 5th.
**Page 10**

**In-Frame and Between-Frame Movement Lines**
✔1) Ask readers if they have a problem with the playback bar cutting off the feet in these examples (pages 17, 18, 19, and 20).

**Global Search**
✔1) practise -> practice (see GitHub Proofreading Book Issue #111)
✔2) front/side/back vs devant/to 2nd/derrière (see GitHub Proofreading Book Issue #111)
✔3) "°" -> "degrees" (in glossary)

**iBox Text**
✔1) decide on a consistent way of describing arms and heads consistently
(Rhonda suggested we should be less specific with the head description and relate it to the arms instead?).
✔2) take out "to the audience" unless specific notation instruction is given? **Decided to leave as is.**

**Reviews**
✔1) Do all reviews.

**Appendix**
✔1) Remove section if not needed.

**About the Authors**
✔1) Update photos or stay with same ones?
**Keeping same photos.**

**Proofreading Guidelines**
Proofread Text:
✔1) Note practise -> practice
✔2) front/side/back vs devant/to 2nd/derrière
✔3) "i" box endings; arms and heads described consistently; "to the audience" used consistently with the use of notation H3 to front?

Proofreading Tips
1) Text (Robyn first, Rhonda last) ✔**Robyn**
2) Links (plus glossary) button and red underline ✔**Robyn**✔**Rhonda**
3) Expanding notation/images/animations ✔**Robyn**✔**Rhonda**
4) Sound icons ✔**Robyn**✔**Rhonda**
5) notation itself  ✔**Robyn**
6) "i" boxes compared to notation (should any terms be linked to Glossary) - note endings of enchainements✔**Robyn**
7) notation compared to animations - note endings of enchainements  ✔**Robyn**
8) decide what gets cut from glossary and then check content (including cross-references) ✔**Robyn**
9) redo all Reviews and make sure instructions, notation, etc., is correct.✔Robyn
10) check pop-up text (including the page 91 widget) ✔Robyn
11) check all title red text to make sure it is spelled correctly and that it refers to the correct chapter and section ✔**Robyn**
12) text in Resources section ✔**Robyn**

**Comment by rryman** [comment]
Sis, may we please discuss some of the above items by phone?

**Comment by rsryman** [comment]
To be added to our list of items to Proofread/check:
1. Sound clips (unless you have done this?)

I tried to make Rhonda's comments below in *italics* but it didn't work starting at "+buttons" instead it inserted an underscore:

Proofreading Guidelines
Proofread Text:
1) Note practise -> practice
*We will go with "practice" throughout iBook3.*
2) front/side/back vs devant/to 2nd/derrière
3) "i" box endings

Proofreading 2) Links (plus glossary) button and red underline, 
_+ buttons for ballet term definitions linked to Glossary Index

Checking version downloaded Sept23/16 1:52 pm:
p. i. the red link launched email but your address was not filled in.
p. ii. I couldn't tell if the iTunes store links for Maddox took me to the US or Can site -- they looked the same.
p. 21 I know I'm supposed to be focusing on links, but I noticed that we list "Adage." Since we use Rose, that should be "Adage, English," although that would really cramp p. 26 so perhaps that's why we left it out? If so, leave as is until readers complain.
p. 24 I noticed an error in the Glossary definition button text: para 2 line 4 "lift the heel" -> "lifts"
p. 52 Another error in the Glossary definition button text line 8-9: "raising front foot" --> "raising the front foot"
p. 89 The PDF link at the bottom of the page launches the Institute notation of Bluebird, which shows the lunge instead of plié in 4th leading into the assemblé; let's hope readers aren't sharp enough to notice the difference! We can always say that our version matches the animation.
Re my photo on pages 97-98, I haven't taken a good head shot in years and I'm looking very haggard lately. I'm happy to go with the photo, but if you can wait until Oct. 7 when I get my hair cut and coloured, I'll take a new shot. Your new photo looks remarkably like your old one, way to go Robyn!
General comment: the Back button seems to be a little more responsive now, if you press on the "sweet spot" - the arrow._

**Comment by rryman** [comment]
**Rhonda**
p. 21 I know I'm supposed to be focusing on links, but I noticed that we list "Adage." Since we use Rose, that should be "Adage, English," although that would really cramp p. 26 so perhaps that's why we left it out? If so, leave as is until readers complain.

**Robyn**
I compromised and put it in on p. 21 and made sure it turns up in the TOC (green background) link as "Adage, English". As you say, if anyone complains about the title on page 26, I'll go to the trouble of trying to fit it in!

**Comment by rryman** [comment]
**Rhonda**
Re my photo on pages 97-98, I haven't taken a good head shot in years and I'm looking very haggard lately. I'm happy to go with the photo, but if you can wait until Oct. 7 when I get my hair cut and coloured, I'll take a new shot. Your new photo looks remarkably like your old one, way to go Robyn!

**Robyn**
Don't worry about it! I'll go with the original photos.

**Comment by rryman** [comment]
Proofreading Guidelines
Proofread Text:
✔1) Note practise -> practice
✔2) front/side/back vs devant/to 2nd/derrière
3) "i" box endings; arms and heads described consistently; "to the audience" used consistently with the use of notation H3 to front?

Proofreading Tips
1) Text (Robyn first, Rhonda last) ✔Robyn
2) Links (plus glossary) button and red underline ✔Robyn
3) Expanding notation/images/animations ✔Robyn
4) Sound icons ✔Robyn
5) notation itself
6) "i" boxes compared to notation (should any terms be linked to Glossary) - note endings of enchainements
7) notation compared to animations - note endings of enchainements
8) decide what gets cut from glossary and then check content (including cross-references)
9) redo all Reviews and make sure instructions, notation, etc., is correct.✔Robyn
10) check pop-up text (including the page 91 widget) ✔Robyn
11) check all title red text to make sure it is spelled correctly and that it refers to the correct chapter and section ✔Robyn
12) text in Resources section ✔Robyn

**Comment by rryman** [comment]
Proofreading comments will go into the Proofreading issue.

**Comment by rryman** [comment]
Proof-reading left to do for Robyn:
1) Linked vocabulary terms.

Proof-reading left to do for Rhonda:
1) Pop-up text.
2) Links that relate from the Appendix to the end of book ... to check Robyn fixed them all!

**Comment by rsryman** [comment]
Rhonda to do the above and report changes in #111 Proofreading Book,  so this issue can be closed
