### ISSUE TITLE
"i" box text - Grand Battement and Battement en Cloche - Page 25 as of 2015/12/19

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#54]
Rhonda, please proofread and see if this format for the "i" boxes for the "Centre Work Without Repeats" is acceptable. I am not able to format it exactly here in GitHub, but at least the content can be edited.

I wasn't sure how to describe the arms and head in the opening position.
 
Anna performs this grand battement and battement en cloche according to the Russian school.
 Music. Andante 4/4 (2 bars)
 Starting Position. Facing downstage left (8), 5th left foot front (arms and head in effacé 			devant pose of the body). 
Bar 1.
Count 1: Left leg grand battement devant just below shoulder height. 			
Count 2: Close 5th front. 
Count 3: Left leg grand battement 2nd just below shoulder height. 			
Count 4: Close 5th back. 
Bar 2.
Count 1: Left leg grand battement derrière to just below shoulder height  (head erect, arms in 3rd arabesque). 			
Counts 2-3: Battement en cloche to effacé devant just below shoulder height. 			
Count 4: Close 5th front.

**Comment by rsryman** [comment]
To be discussed via Hangout:
Vaganova actually doesn't use the term cloche but rather balancé (like the swing of a pendulum). 
Updated title: Grand Battement Jeté and Balancé. You'll need two labels:
Grand Battement Jeté, Russian and Grand Battement Jeté Balancé, Russian
I'll work on the glossary definitions.

I find the 2-ct cloche action very sluggish. See comparison in the animation uploaded to Dropbox Ch3 folder: CH3GrandBattement&ClocheV3.m4v (I uploaded .mv4 format because the .mov was 50MB) 
TO BE DECIDED: whether to use the version with or without the BMN legato line.

Also to be determined: do you like Anna's higher cut leg in the stage right figure or the black on the thigh of the stage left figure (this is what we had been using, I hadn't noticed before now).

Another complication: Vaganova says the body must be involved in the swing. This would be explicitly notated as a back tilt on Bar 2 ct 3. The forward torso is understood on an arabesque that high, yes? 
See animation uploaded to Dropbox Ch3 folder: CH3GrandBattement&ClocheV4.mov

Suggestion re updated i-box text:

Anna performs this sequence according to the Russian school. Each battement is shown to just below shoulder height but is understood to be as high as the dancer's technique allows.
 Music. Andante 4/4 (2 bars)
 Starting Position. Facing downstage left (8), 5th left foot front (arms and head in effacé devant pose of the body). 
Bar 1.
Counts 1-2: Left leg grand battement jeté devant.  Close 5th front. 
Counts 3: Left leg grand battement jeté à la seconde.  Close 5th back. 
Bar 2.
Count 1: Left leg grand battement jeté derrière (head erect, arms in 3rd arabesque). 
Count 2: Retain 3rd arabesque. 
Count 3: Battement jeté balancé to effacé devant.
Count 4: Close 5th front.

**Comment by rsryman** [comment]
After our Hangout we decided the following:

Use Jenna and leave title and notation as is. 
Glossary definitions will cross-reference RAD/Cecc/Vag terminology.
I have deleted all old animations from Dropbox. See revised uploaded animations, front & back views:
CH3GrandBattement&ClocheFR.mov
CH3GrandBattement&ClocheBK.mov

Revised i-icon text (in Book 2 Chapter 7 Jumps with Music, this format always related to one of the 3 schools. I had to use more word to describe each movement, generically here, as prior to Bk2 Ch7. Please check format re description of head, etc. I could not keep checking all 3 books):

Jenna performs this grand battement sequence. Each battement is shown to just below shoulder height but is understood to be performed as high as the dancer's technique allows.
 Music. Andante 4/4 (2 bars)
 Starting Position. Facing downstage left, 5th left foot front (effacé) (right arm overhead, left arm in 2nd, head turned right and raised). 
Bar 1.
Count 1: Left leg grand battement devant. 
Count 2: Close 5th front. 
Count 3: Left leg grand battement 2nd.
Count 4: Close 5th back. 
Bar 2.
Count 1: Left leg grand battement derrière (arms in arabesque line, left forwards and right back; head erect). 
Counts 2; Sustain the arabesque.
Count 3: Swing left leg through 1st position to devant (head and arms as Bar 1 count 1). 
Count 4: Close 5th front.

**Comment by rryman** [comment]
Are we taking out Battement Cloche in the title, as we make no mention of it in the "i" text now that you have updated it. Not sure how you see the terms being linked from this page. Title "Grand Battement" and the name of the step in each school under the title and linked to glossary definitions?

As we spoke about on the phone, I changed the head to match the animation. I also had to change the height of the arms in arabesque to match the changes you made in the animation. I also reflected these changes in the "i" box. I changed the wording of the arms at the end to "as in Starting Position" as that is where they are described.
![grandbattementpage25](https://cloud.githubusercontent.com/assets/15850667/11920564/61586b4c-a741-11e5-900f-dfc5ff10c09c.jpg)

The "i" box now reads:
Jenna performs this grand battement sequence. Each battement is shown to just below shoulder height but is understood to be performed as high as the dancer's technique allows. 
Music. Andante 4/4 (2 bars)
Starting Position. Facing downstage left, 5th left foot front (effacé) (right arm overhead, left arm in 2nd, head slightly inclined and turned right, and raised). 
Bar 1.
Count 1: Left leg grand battement devant. 
Count 2: Close 5th front. 
Count 3: Left leg grand battement 2nd. 
Count 4: Close 5th back. 
Bar 2.
Count 1: Left leg grand battement derrière (arms in arabesque line, left forward and right back; head erect). 
Count 2: Sustain the arabesque. 
Count 3: Swing left leg through 1st position to devant (arms and head as in Starting Position).
Count 4: Close 5th front.

**Comment by rsryman** [comment]
Yes, Let's just use Grand Battement in the title. I'll need to do the Glossary before we can decide how many terms can be linked on this page.

**Comment by rryman** [comment]
Okay. When you are next working on the book, if you feel the changes to the notation and the "i" box above are okay, then please close this item.

**Comment by rsryman** [comment]
Before we close this item, should we discuss consistency re restating the working foot (when it doesn't alternate?) in the i-box text description. We decided not to restate it in the Adage. 
TO BE DISCUSSED BY HANGOUT before we proceed?

**Comment by rsryman** [comment]
I see you have changed the title of p. 25 but we still need to decide on wording before I can close this item or continue proofreading i-box text. 

Also:
p. 20: remove "en cloche" from para 1 line 2.
We avoid mentioning specific terminology in most of BB7, but have explained terminology re foot to leg (p. 16) because we use the specific dancers. Should we make a statement on p. 20 (footnote the word "battement" cf format on p. 16): This swinging action is called battement en cloche in the English school and battement balancé in the Italian and Russian schools.

**Comment by rryman** [comment]
I have added the footnote on page 20.

You wanted the repetition of the right leg in the adage "i" box taken out.
However, on page 26 the right leg doesn't close so it isn't confusing.
On page 25 the left leg closes, so it is conceivable the right leg could do the second grand battement so I believe this is a different case. If you don't want the left leg repeated then I suggest we say something like: This sequence is performed with the left working leg. However, I am just not sure where to put it in the formatting of the "i" box?

**Comment by rsryman** [comment]
In a simple sequence like this it seems OK to repeat "left leg" as you have it now, but we don't mention a specific leg on the previous page re Battement tendu. Perhaps we should establish guidelines. I'll open an issue called "i-BoxTextGuidelines."

**Comment by rryman** [comment]
Okay.
