### ISSUE TITLE
Add EntrQuatreEntrRoyalFR.mov + EntrQuatreEntrRoyalBK.mov to book

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook3#6]
I have uploaded the 2 updated animations to Dropbox (repeated with burgundy foot). 

Please watch and if OK add to book:

https://www.dropbox.com/s/zhqktj4o4doc6kj/EntrQuatreEntrRoyalFR.mov?dl=0
https://www.dropbox.com/s/8uouxaalhqaal5c/EntrQuatreEntrRoyalBK.mov?dl=0

**Comment by rryman** [comment]
Rhonda, I am attaching the notation we had for EntrQuatreEntrRoyal.
When I watch your animation it looks to me like she is not straightening her knees on the musical count 2 of bar 7 as we have notated it. If you want Maria to straighten on musical counts 1&2 of bar 8 then I will need to update the notation and use an exclusion bracket instead of FIN.
Please let me know if you want to change the animation, or you would like me to change the notation.
[p122EntrechatQuatreRoyal.pdf](https://github.com/rryman/BeneshForBalletBook3/files/41139/p122EntrechatQuatreRoyal.pdf)

**Comment by rsryman** [comment]
Yes, you are right. To my eye, she re-stretches on Bar 16 count 1 (or perhaps counts 1-2?) of the repeat.

Re-stretching on Bar 15 ct 2 would look very abrupt, but let's discuss what we need to show regarding FIN versus exclusion bracket. I know we use the latter in the Tour Enchaînement. Is there another good example of FIN?

**Comment by rryman** [comment]
Robyn to update notation to straighten on count 16 (using legato line starting from Bar 15 ct 2 and ending on Bar 16 ct 1). Therefore Robyn needs to use an exclusion bracket.

**Comment by rryman** [comment]
Rhonda, please check this notation and let me know if you want anything changed.
[EntrechatQuatreRoyal.pdf](https://github.com/rryman/BeneshForBalletBook3/files/42954/EntrechatQuatreRoyal.pdf)

**Comment by rsryman** [comment]
The notation is fine. Using part-bar repeats to eliminate the anacrusis will be simpler. I know the i-icon text is strictly correct but it might be simpler just to say "Restretch" on Bar 16 ct 1. The phrasing could be understood as part of the technique? Something to run by a reader? I suspect people like Susanna will want all details while practitioners would prefer less. Let's leave as is for now.

**Comment by rsryman** [comment]
The notation and i-icon text is checked, but one suggestion: 
Bars 5-7: "…head erect, then lowering…"
You can delete the two blue "reminders on page 56, but let's leave the pop-up issue for now, OK?

I think this issue can be closed for now, yes?

**Comment by rryman** [comment]
"i" box info updated 2/12/2015.
