### ISSUE TITLE
Chapter 5 - Plie

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#74]
We had also discussed giving examples of empty repeat bars with "in 1st, 2nd, 4th, 5th" and "en croix", etc., as that is used quite often in the RAD Set Exercises and Variations. Do you still want to do that, and if so where does it belong? At the beginning of BB8, or just in as examples in Ch5 with a pop-up explanation?

**Comment by rsryman** [comment]
I think BB8 is quite full of content.

We can make sure we cover this in CH5 plié ("in 1st, 2nd, 4th, 5th") and tendu ("en croix") examples, preferably based on published RAD exercise settings. Explanations in pop-ups or i-box text? To be determined.

**Comment by rryman** [comment]
Okay. What is the copyright issue re using a published RAD exercise? Should we use an old grades one or something ... not the new syllabus?

**Comment by rsryman** [comment]
I think we should NOT do the exact exercise but a simplified version. The RAD doesn't have a copyright on plié or tendu class exercises, etc. Any change makes it a unique exercise. Just pick something very basic, probably around old Elementary (current Inter 1??) level. We can do this together via Hangout if you like.

**Comment by rryman** [comment]
How about this one modified quite significantly?
Do it as a Centre Exercise to a Waltz 3/4.
Take out the introduction and sub-beats.
Do only one demi-plie and one full plie; rise, lower, pointe, lower new position (1-8 counting one dancer's count per bar).
Do in 1st 1-8; 2nd 1-8; 5th 1-8, and 4th 1-8.
[01_plie_IF_2.pdf](https://github.com/rryman/BeneshForBalletBook3/files/78980/01_plie_IF_2.pdf)

**Comment by rsryman** [comment]
Yes, this a basic setting that builds slightly from the one we show on pp. 33-34. Omit the head (since in centre work it would alternate) except on the transitions?

But I'm not sure of the timing you suggest. Each phrase in the pdf version takes 8 bars of 2/4 (16 Dancers' counts). Modified in 8 bars of 3/4 (described using RAD terms:

Music. Waltz 3/4 (32 bars: 8 bars or 8 Dancer's Counts per phrase)
Starting Position. en face, 1st position (arms 1st).
Bars 1-2 Demi-plié (arms "breathe" through demi-2nd to 2nd).
Bars 3-6 Grand plié (full port de bras).
Bar 7: Rise (take 2 cts) and start lowering.
Bar 8: Count 1. Lower to 1st flat.
           Count 2. Dégagé side.
           Count 3. Lower into 2nd position (arms 1st).
Repeat Bars 1-8 in 2nd, 4th, then 5th, with a dégagé transition in the eighth bar of each phrase (Dancer's Count 8).

Introduce the sequence in 1st, then repeat exactly as notated but in 2nd, 4th, then 5th? Use an exclusion bracket over Bar 8, show 7 empty bars (or say "7 bars") and notate each transition in the 8th empty bar (Dancer's count 8)? 

I could animate this as a start, once you confirm the above.

**Comment by rryman** [comment]
I will work on updating the notation now.

**Comment by rryman** [comment]
Take a look at the attached PDFs. Will this work? Have I made any errors?
Which version do you prefer?
[Ch5Plie.pdf](https://github.com/rryman/BeneshForBalletBook3/files/80113/Ch5Plie.pdf)
[Ch5PlieTest.pdf](https://github.com/rryman/BeneshForBalletBook3/files/80114/Ch5PlieTest.pdf)

**Comment by rsryman** [comment]
Very beautiful work. I think I prefer the compact version in
Ch5PlieTest.pdf.
Might be useful to have the alternate version in an Appendix?

Can you split the empty bar text on 2 lines (before the word "Bars")?
Can you make the in front signs a bit less wide in arms bras bas?
Same for the in front & behind signs for 4th (pos of the feet) opposite 5th.
In Book 1 we showed the open 5th positions (Engl and Ital) well above head
height, with wrists facing out. In this setting the rise is relatively
fast, so I agree that we should use a lower position, but perhaps show
wrists facing down (rather than unqualified)?
Perhaps leave head turned at end?

I thought we were leaving the head erect except for the change of position,
and that's how I animated the version I just uploaded to
Dropbox: CH5PliéFR15fps.m4v
(interim version for your comments, to be refined based on your BMN)

**Comment by rryman** [comment]
As per our Google Hangout discussion, I have updated the notation and added it to the book.
Once you have determined if you can use a 3/4 metronome beat, we will decide on which version of the animation to use

**Comment by rsryman** [comment]
I have uploaded a file with 3/4 metronome beats which I think works well:
CH5PliéFR30fps.mov

When you confirm this, I'll do the back view.

**Comment by rryman** [comment]
Have you watched this movie file? Jenna looks like she gets out of time when she does the pointe tendu. Is it just how it plays on my computer?

**Comment by rsryman** [comment]
The problem is it's a long sequence and gets slightly out of time as it goes on. I'll try to fine tune it some more.

**Comment by rryman** [comment]
But isn't it out of time on the first tendu which is only 8 bars?

**Comment by rsryman** [comment]
It looks fine in DanceForms but the export algorithm does something weird
to the start and end. I just uploaded another try.

**Comment by rryman** [comment]
This one is better. Thanks.

**Comment by rsryman** [comment]
[Not to myself: if the timing goes askew, check that the Panel pointer is exactly centred, since DanceForms exports at the default frame rate not the Panel setting.]

Back view uploaded: CH5PliéBK30fps.mov

**Comment by rryman** [comment]
CH5PliéBK30fps.mov added to the book.

Rhonda, I suggest you start an issue called "helpful hints" for yourself and add the above hint to it so you can easily find it.

**Comment by rsryman** [comment]
Right.
