### ISSUE TITLE
Proofreading BeneshBasics8 Ch4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#76]
I have completed Chapter 4 to the best of my ability. When you feel in the mood, please download the most recent version on the book and proofread the text, the notation, formatting, etc.
Please create an issue for each page with a title something like:
BeneshBasics8 Ch4 Title Page (P 34 as of 2016/month/day)
BeneshBasics8 Ch4 Same Side Repeats (P 35 as of 2016/month/day)
etc.
Please use the "Proofreading" label and assign it to me.
Thanks :)

**Comment by rsryman** [comment]
I am starting to go over BB8 (pp. 33-40) in preparation for writing BB9. We can do a Hangout to  discuss these suggestions before you make any changes. I have used our Word Template to match font size and layout; it contains old BMN and animations just as place markers.

p. 33: See uploaded file:  Ch4BB8p33.docx
Perhaps the page should be a lighter, less theoretical intro to repeats. I have suggested updated text in para 1, with the rest of the page content staying as is.  We can decide whether the Taglioni "sticky"/footnote should go here or on p. 41 (more relevant, and more room?).
Wording to be discussed: "…coincide with musical bars" OR "…coincide with musical bar lines" OR "…coincide with bar lines." 

p. 34 See uploaded file:  Ch4BB8p34.docx
Can you move the 2nd graphic (repeat signs with same side markings) down a bit to make each stand out on its own (align its bottom with bottom of para 1 line 4)? Suggested edit re para 2 text and format. 

p. 35 There seems to be room for another explanatory line at the bottom. If so, what about: 
To show the **number of bars** corresponding to the repeated phrase, "**3 bars**" is written following the end *repeat* sign. This method [or format??] is used throughout the published *RAD Set Exercises and Variations.*  [titles in italics; use only if this is the exact title]

p. 36 To correspond to the previous page format, add a sentence below the bottom notation:
To show the **bar numbers** corresponding to the repeated phrase, "**Bars 2-4**" is written following the end *repeat* sign. 

p. 37  "3 basic types" --> "three basic types" 
          Move bottom right graphic to the left a bit (to balance right graphic)
Will this revised top sentence fit: "In Book 2 you learned how to read jumps. These simple allegro sequences illustrate the three basic types of repeats."

p. 38 Consider adding a line break before sentence 2 at bottom, to offset it?
Can we discuss putting the small graphic for each type of repeat in the top line beside the title of the page rather than beside the top para? it then becomes like a label for the page, and doesn't get squashed at the right side.

p. 39 line 4: "…, and finish" --> "…, but finish"

p. 40 Do I remember that we said we should try to be informal and not use "i.e." ? Could we say: "When the final frames indicating the last beats of the …"

Moving into Chapter 5, there are some considerations that impact BB8 :
p. 41 We may prefer to add the Taglioni information here rather than p. 33
pp. 42-43 We haven't actually introduced the theory of using empty repeat signs (no markings) and word descriptions, although this may be self-evident, and also clarified by the i-box text. 
I have therefore uploaded suggested revisions to p. 33: Ch4BB8p33(alternative).docx
Also uploaded suggested new p. 41: Ch4BB8_NEWp41.docx

**Comment by rryman** [comment]
Implemented via Google Hangout.
New page 41 and 42 still to be completed. Rhonda to create animations and handwritten notation.

**Comment by rsryman** [comment]
See uploaded file: Ch4BB8_NEWpp41-42.docx

Animations to follow asap.

**Comment by rsryman** [comment]
Robyn I just updated the word file "Ch4BB8_NEWpp41-42.docx" with the following info, so please  use to create the BMN. You can use:

Plié in 1st and 2nd, p.22. Tempo: Largo (Please add legato line over plié, but not tendu)
Reverse Repeats to create En Croix repeats (p. 41). Tempo: Andante.

See animations uploaded:
BB8EmptyRepeatsBK.mov
BB8RepeatsEnCroixBK.mov

**Comment by rryman** [comment]
Thanks! All added to the book.
The only thing left to decide on is:
Whether the Taglioni "sticky"/footnote should go here or on p. 43 as the introductory paragraph (more relevant, and more room?).
