### ISSUE TITLE
Sub-beat Redundancy

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook3#92]
Given the use of the "redundant" sub-beats in the published RAD Set Exercises and Variations, how do you feel about adding a note to the bottom of page 39 and/or a pop-up on pages 46 & 47?

We state the redundancy rule in _Benesh for Ballet: Book 2_ without mentioning that the sub-beats are notated in the published RAD Set Exercises and Variations. Maybe we can add a note in _Benesh for Ballet: Book 3_ (when we use examples without the sub-beats) saying something like:
"For clarity the sub-beat signs may be included, as in some exercises in the published RAD Set Exercises and Variations."???

**Comment by rsryman** [comment]
TO BE DISCUSSED? On p. 39, if there room for a note at the bottom add: 
The "an" (graphic?) sub-beats are normally omitted when actions occur on every half-beat in a bar (see Book 2 p. 118). They may, however, be shown for clarity, as in some exercises in the published RAD *Set Exercises and Variations.*

Perhaps we should add sub-beats to the second stave? If so & depending on room, the wording at the bottom of the page could be:
The "an" (graphic?) sub-beats are normally omitted when actions occur on every half-beat in a bar, as in the first stave (see Book 2, p. 118). They may, however, be shown for clarity, as in the second stave.[Footnote]
 
[Footnote] This practice is used in some exercises in the published RAD *Set Exercises and Variations.*

Also, perhaps add a pop-up on p. 46, since there are no term labels? Show a tiny Bar 1 with an-beats & note:
The "an" sub-beats are shown here for clarity. This practice is used in some exercises in the published RAD *Set Exercises and Variations.*

**Comment by rryman** [comment]
I have uploaded an updated version of the book to Dropbox.

Please look at Page 39, 46, and 47.
This implementation made the most sense to me as I was working with the book, but if you don't agree with it please give me a call and we will discuss it via Google Hangout.

**Comment by rsryman** [comment]
One comment about the wording of the explanation: I think "When applying the BMN redundancy-avoidance principle," is a misplaced clause or some grammatical anomaly. What about:
"According to the BMN redundancy-avoidance principle, sub-beats are omitted when…." OR
"According to the BMN redundancy-avoidance principle, sub-beats may be omitted when…."

p. 39: Can you try taking it down a font size so it fits on 4 lines, right justified with the end of the BMN stave?
pp. 46 & 47: I like the graphic at the top of the page as on p. 47 if possible.

**Comment by rryman** [comment]
Changes have been implemented. Can we close this now?
